{
 "title": "Nginx Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Nginx Overall Response ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | Status_Code = \"200\" [7d])) by (Status_Code))\n"
    },
    {
     "expr": "\n(sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | Status_Code != \"\" [7d])) by (app))"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | Status_Code != \"\" [7d])) by (Status_Code)",
     "legendFormat": "{{Status_Code}}"
    }
   ]
  },
  {
   "title": "Request Type Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} != \"${jndi:ldap://log4shell-generic-k4knsY3lwLt1L5Tm8xWr${lower:ten}.w.nessus.org/nessus}\"| regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | Method != \"\"  [7d])) by (Method)",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "Maximum Byte(s) Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` |unwrap Bytes | __error__=\"\" [7d]) by (app)"
    }
   ]
  },
  {
   "title": "Total Visits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | User!=\"\" [7d])) by (app)",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "Visits each user",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | User!=\"\" [7d])) by (User)",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "Unique Visits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` | User!=\"\" [7d])) by (User))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Invalid Users Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} |= \"was not found\" | regexp `(?P<Header>\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+) \"(?P<User>\\S+)\"` | User !=\"\" [7d])) by (User))"
    }
   ]
  },
  {
   "title": "Invalid Access Attempt Users",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} |= \"was not found\" | regexp `(?P<Header>\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+) \"(?P<User>\\S+)\"` | User !=\"\" [7d])) by (User)",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "Invalid Access Attempt Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"}  |= \"was not found in\" [7d])) "
    }
   ]
  },
  {
   "title": "ERROR Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\",app=\"nginx-new\"} | regexp `(?P<IP>\\S+) - (?P<User>\\S+) (?P<Date>\\S+\\s+\\S+) \"(?P<Method>\\S+) (?P<URL>\\S+\\s+\\S+) (?P<Status_Code>\\S+) (?P<Bytes>\\S+)` |= \"[error]\" [7d])) "
    }
   ]
  },
  {
   "title": "ERROR log lines",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 43 },
   "targets": [
    {
     "expr": "{namespace=\"default\",app=\"nginx-new\"}  |= \"[error]\""
    }
   ]
  },
  {
   "title": "Nginx Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx_exporter\"}",
     "legendFormat": "Availability"
    }
   ]
  }
 ]
}